{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nemotron-inference.serviceAccountName" . }}
  labels:
    {{- include "nemotron-inference.labels" . | nindent 4 }}
  {{- if and .Values.serviceAccount.workloadIdentity.enabled .Values.serviceAccount.workloadIdentity.gsaEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.workloadIdentity.gsaEmail | quote }}
  {{- end }}
{{- end }}
